version: '3.8'
services:
  discography-db:
    image: mongo:latest
    container_name: discography-mongo
    environment:
      MONGO_INITDB_DATABASE: discography
    volumes:
      - discography-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - discography-net

volumes:
  discography-data:

networks:
  discography-net:
    driver: bridge
